name: code scanning

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Jest
        run: yarn test

      - name: Collect coverage
        run: yarn test:coverage

      - name: Check code coverage
        run: |
          yarn test --coverage
          npx check-coverage --statements 80 --branches 70 --functions 80 --lines 80 coverage/lcov.info

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run lint:fix
        run: yarn lint:fix
