name: "Code Scanning analysis"

on:
  push:
    # this workflow would be executed at any push event to master or develop branches
    branches: [ master, develop ]
  pull_request:
    # this workflow would be executed at any pull request event with base branch master or develop
    branches: [ master, develop ]
  workflow_dispatch:
    # this workflow would be executed when a workflow_dispatch event is executed (via API or manually)

jobs:
  CodeQL:
    # uses code-scanning javascript workflow
    uses: mercadolibre/fury_code-scanning-workflow/.github/workflows/js.yml@master
    secrets:
      external-repository-token: ${{ secrets.CODE_SCANNING_EXTERNAL_REPOSITORY_TOKEN }}
      configs-url: ${{ secrets.CODE_SCANNING_CONFIGS_URL }}